packages:
  - packages/*
  - clients/**/*
  - examples/**/*
  - docs
  - bot

catalog:
  zod: 3.25.23
  typescript: 5.8.3
  ai: 4.3.16
  tsup: 8.3.6
  vitest: 3.0.5
  '@ai-sdk/anthropic': 1.2.3
  '@ai-sdk/groq': 1.2.2
  '@ai-sdk/openai': 1.3.5
  '@ai-sdk/provider': 1.1.0
  '@ai-sdk/ui-utils': 1.2.3
  '@ai-sdk/google': 1.2.17
  '@openrouter/ai-sdk-provider': 0.4.5
  '@modelcontextprotocol/sdk': 1.12.0
  '@types/bun': latest
  '@tavily/core': 0.3.1
  discord.js: 14.18.0
  '@octokit/rest': 21.1.1
  hyperliquid: 1.7.5
  composio-core: 0.5.18
  chalk: 5.4.1
  zod-to-json-schema: 3.24.3
  uuid: 11.1.0
  h3: 1.15.1
  unstorage: 1.15.0
  '@e2b/code-interpreter': 1.0.4
  dotenv: 16.4.7

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@tailwindcss/oxide'
  - bufferutil
  - canvas
  - esbuild
  - hyperliquid
  - protobufjs
  - sharp
  - utf-8-validate
