name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of release (prerelease, prepatch, patch, minor, preminor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - prerelease
          - prepatch
          - patch
          - minor
          - preminor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Protobuf Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install dependencies
        env:
          HUSKY: 0
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Ensure prepublishOnly hooks
        run: |
          chmod +x scripts/add-prepublish-hook.sh
          ./scripts/add-prepublish-hook.sh

      - name: Build packages
        run: pnpm run build:packages

      - name: Run tests
        run: pnpm test || echo "No tests configured"

      - name: Version packages with Lerna
        id: version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Version packages with lerna (without publishing)
          pnpx lerna version ${{ github.event.inputs.release_type }} --conventional-commits --yes --no-private --force-publish --ignore-scripts --no-push

          # Get the new version tag
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Publish packages with pnpm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Find all packages and publish them using pnpm
          for package in packages/*; do
            if [ -d "$package" ] && [ -f "$package/package.json" ]; then
              # Check if package is private
              IS_PRIVATE=$(cat "$package/package.json" | jq -r '.private // false')
              
              if [ "$IS_PRIVATE" != "true" ]; then
                echo "Publishing $(basename $package)..."
                (cd "$package" && pnpm publish --no-git-checks --access public)
              else
                echo "Skipping private package: $(basename $package)"
              fi
            fi
          done

      - name: Push tags and commits
        run: |
          git push --follow-tags

      - name: Generate Release Notes
        id: release_notes
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.before || 'HEAD~1',
              head: 'HEAD'
            });

            const releaseNotes = commits.commits
              .map(commit => `- ${commit.commit.message.split('\n')[0]}`)
              .join('\n');

            return releaseNotes;

      - name: Create GitHub Release
        uses: actions/github-script@v7
        env:
          TAG: ${{ steps.version.outputs.TAG }}
        with:
          script: |
            const fs = require('fs');
            let body = '';

            // Try to read CHANGELOG.md
            try {
              if (fs.existsSync('CHANGELOG.md')) {
                body = fs.readFileSync('CHANGELOG.md', 'utf8');
              }
            } catch (e) {
              body = ${{ steps.release_notes.outputs.result }} || 'No changelog provided for this release.';
            }

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.TAG,
              name: `Release ${process.env.TAG}`,
              body: body,
              draft: false,
              prerelease: ${{ contains(github.event.inputs.release_type, 'pre') }}
            });
